device: "cuda"
dataset_name: "jainr3/diffusiondb-pixelart"
dataset_config: "2k_all"

batch_size: 10
learning_rate: 0.0002
epochs: 30

min_image_size: 16
max_image_size: 64

block_out_channels: [64, 128]
channels: [256, 512, 1024]
norm_groups: 32

out_dir: "./output"
save_dir: "./models"