# device configuration
device: "cuda"

# dataset configuration
dataset:
  name: "jainr3/diffusiondb-pixelart"
  config: "2k_all"
  batch_size: 10

# image configuration
image:
  min_size: 16
  max_size: 64

# model architecture
models:
  unet:
    block_out_channels: [64, 128]
    channels: [128, 256, 512]
    norm_num_groups: 32
  vae:
    block_out_channels: [64, 128]
  clip:
    model_name: "runwayml/stable-diffusion-v1-5"
    max_length: 77
    guidance_scale: 7.5

# training configuration
training:
  learning_rate: 1e-4
  epochs: 80
  optimizer:
    type: "adamw"
    betas: [0.9, 0.999]
    weight_decay: 0.01
  lr_scheduler:
    type: "constant"  # "constant", "cosine", "warmup_cosine"
    min_lr: 1e-6      # nur bei cosine/warmup_cosine
    warmup_steps: 500 # nur bei warmup_cosine
  classifier_free_guidance_prob: 0.1  # 10% unconditional training

# checkpointing configuration
checkpointing:
  save_best: true
  save_frequency: null  # null = nur best model, sonst alle X epochen
  keep_top_k: 3  # behalte nur die 3 besten modelle

# tensorBoard configuration
tensorboard:
  enabled: true
  log_dir: "./models/tensorboard"
  metrics:
    log_frequency: 10  # alle 10 batches
    log_histograms: false
  validation:
    frequency: 5  # alle 5 epochen
    prompts:
      - "pixel art house"
      - "pixel art car"
      - "pixel art character"
    inference:
      timesteps: [800, 400, 50]
      guidance_scale: 7.5
      grid_size: 32

# directories
paths:
  output_dir: "./output"
  save_dir: "./models"
  tensorboard_dir: "./models/tensorboard"
  checkpoints_dir: "./models/checkpoints"